version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
  reviewers:
  - 9renpoto
  ignore:
  - dependency-name: eslint
    versions:
    - 7.2.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
